version: '3'

volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13.11
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: misha1113/kittygram_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media_volume:/app/media
    depends_on:
      - db 
  frontend:
    image: misha1113/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: misha1113/kittygram_gateway
    env_file: .env
    depends_on:
      - backend
    volumes:
      - static_volume:/static/
      - media_volume:/app/media
    ports:
      - 9000:80 